### ISSUE TITLE
Structure LG 2-6, clarify SOLID contains architecturally relevant principles

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#139]
these heuristics have been created for C++ programmers, and they strictly address OO systems.

change LG to reflect their architectural relevance, instead of focussing on OO details

**Comment by gernotstarke** [comment]
at least rephrase, to focus on the "architectural impact".

Don't refer to "classes", but components. Explicitly mention that we don't mean SOLID to represent the programming rules.

**Comment by alxlo** [comment]
Maybe I have missed it, but I could not find a reference to SOLID as a whole in the curriculum.Definitely not in LG-2-6 which would be the right place for it. There are only some parts of SOLID mentioned. I propose the following:
- Declare LG-2-6 overall as "R1-R3" instead of "R1". We have to declare it "R1-R2" anyway, as it already contains an R2 principle. 
- Mention SOLID as R3 and note that it relates to OO systems but some fundamental ideas behind it are relevant for architecture.
- Explain the relation between Single Responsibility (already in curriculum) and SoC (R1, already in curriculum)
- Keep Open/Closed as R1 - it's relevant on an architectural level
- Add "Principle of Least Surprise" (R1 or R2 - I'm all in for R1) and, mention Liskov Substitution (R3) as one expression of this principle and highlight its relation to consistency and conceptual integrity.
- For Interface Segregation relate do LG 2-9 (Design and define interfaces)
- Keep Dependency Inversion (R1) as one fundamental principle to design the direction of dependencies and mention the relation to the concept of required/provided interfaces.

Additionally:
- Add "Expect errors" as an R2 (or even R1?) design principle to satisfy the wish of some to include Postel's Law and Murphy's Law. Without re-opening the discussion about Postel's Law: Designing system in an error resilient way is something we should mention as desirable.

**Comment by alxlo** [comment]
@alxlo will sketch up a draft on this confluence page https://confluence.isaqb.org/pages/viewpage.action?pageId=47355991

**Comment by alxlo** [comment]
Now there is a first draft on the confluence page. As this learning goal in itself covers A LOT of ground, there might be quite a lot of feedback to be considered. Also the relevance for exams is denoted with a much finer granularity, just because this LG is so big and we should be able to highlight the more relevant parts.

Pleases note

- that SOLID is only R3 (=it can be omitted) but some of the SOLID principles will have to stay as they are applicable on an architectural level, I hope this is properly conveyed.
- **Simplicity** has been added, most trainers will talk about KISS and YAGNI anyway
- **Expect Errors** has been added, reasons same as simplicity and there were voices that wanted an anchor for Postel's law.
- **Abstraction** has been clarified, as just having a single word there was quite ambiguous.

**Comment by gernotstarke** [comment]
formatting the LG is an adventure...

**Comment by gernotstarke** [comment]
done...
