### ISSUE TITLE
DE: Begriffsklärung "Entwurf" (meaning both draft and design)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#272]
The term "Entwurf" in German has the following two meanings:

* draft version of something
* design something

When using the term "Architekturentwurf", it can either be the activity of designing an architecture (which is intended), but can also mean "draft version of the architecture" (which is NOT intended).

We should clarify that.

Thanx to Deniz and Enrico for pointing out this ambiguation!

**Comment by alxlo** [comment]
Which part or LG of the curriculum does this refer to? Because understanding this depends a lot of context. I totally agree on "Entwurf" addressing both the design process and the result of the design process (same problem in English with "design") and we might clarify if we mean the first one or the second one.
Sidenote: The connotations of "draft" and "Entwurf" are not very - but just slightly - different but that doesn't matter if we only address the process.

**Comment by mikesperber** [comment]
Added a draft pull request to address the issue.

**Comment by gernotstarke** [comment]
when we clarify terms, we need to update our definitions in the glossary accordingly (or add some, if these were missing)

**Comment by rhoadesre** [comment]
Is there a concrete todo for this issue regarding the curriculum or is this issue completed with the update of the glossary?

**Comment by gernotstarke** [comment]
let's close it here, as it is open in the glossary repository.
