### ISSUE TITLE
LG-01-03: Misleading English translation

### ISSUE THREAD

**Issue by ulibecker** [isaqb-org/curriculum-foundation#523]
"Gesamtverantwortung der Projektleitung" is currently translated as "overall responsibilities of project management", which rather means "die allgemeinen Aufgaben des Projektmanagements"

IMO "overall project responsibility" would be more suitable here - @rhoadesre what do you think?

**Comment by gernotstarke** [comment]
@ulibecker could you please open a PR with your proposed change, in a branch named #523-misleading-translation?

@bertjan - any opinion from your side?

**Comment by bertjan** [comment]
I've read the German and English learning goal description a couple of times and I do think there's room for improvement ;-)
I think the current wording is a bit confusing, both in German and in English.

> Sie müssen diese Verantwortung mit der Gesamtverantwortung der Projektleitung oder anderen Rollen koordinieren.

> they must align this responsibility with the overall responsibilities of project management and/or other roles

We're talking about the architect's responsibility of meeting requirements and designing the architecture. Obviously, the architect needs to coordinate & align this with other roles in the project.

We're currently mentioning "Projektleitung" and "project management" which I find a bit confusing because it could mean both a role/responsibility (the person / persons doing the leadership of the project) or an activity (the act of leading / managing a project).

We could either make it clearer that we mean an *activity* (I think that's what @ulibecker is suggesting, which is fine by me), or make it a bit more formal and mention a *role* instead of an activity, for example "Projektleiter" and "project manager".

A suggestion: 

> Sie müssen diese Verantwortung mit der Gesamtverantwortung der Projektleiter oder anderen Rollen koordinieren.

> they must align this responsibility with the overall project responsibility of the project manager and/or other roles

Because we also say "anderen Rollen" and "other roles", to me it makes sense to also use Projectleiter / Project manager as a role.

Looking a bit further at this I found something interesting. In https://github.com/isaqb-org/curriculum-foundation/blob/main/docs/01-basics/LZ-01-05.adoc where we describe the relationship to other stakeholders, we mention the activity in the German description and the role in the English description:
> Projektleitung und -management

> project managers

So whatever we choose to do in https://github.com/isaqb-org/curriculum-foundation/blob/main/docs/01-basics/LZ-01-03.adoc, we should also do in  In https://github.com/isaqb-org/curriculum-foundation/blob/main/docs/01-basics/LZ-01-05.adoc

My preference is use "Projektleiter" and "project manager". Being a non-native German and English speaker, those words have the clearest meaning to me and the least amount of ambiguity.

Sorry for taking this discussion a bit deeper than it was ;-)
