### ISSUE TITLE
missing "table of learning goals" in DE and EN

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-foundation#58]
From review by Sevda Cagirici:

"Im Vergleich zur früheren Curriculum Version gibt es jetzt kein „Verzeichnis der
Lernziele“."

**Comment by gernotstarke** [comment]
NOT critical for V5 - but would be really nice.. also for the upcoming advanced-curricula (therefore I add Ben to assignees)

**Comment by rdmueller** [comment]
As there is no such feature in AsciiDoc, I would suggest to solve this with a simple gradle task.
As I do understand, you need a list of special headlines or anchors. For instance

    === Lernziel 2-6:
or
    [[LZ-2-6]]
 
So, we could loop over all documents and search for these lines with a regular expression.
We then could create an `.adoc`document with the gathered information and include it in the main document.
Problem could be the sort order but since all tags start with the same prefix and are numbered, I guess this will not be a big issue.

The following task could be a could basis for such a gradle task:

https://github.com/docToolchain/docToolchain/blob/master/scripts/collectIncludes.gradle

I would be more than happy to implement it for you.

**Comment by p-goetz** [comment]
Thank you very much, @rdmueller for the information and hints. That really helps. I would like to learn more about AsciiDoc and this seems like a good opportunity to dive deeper into it. 
May I come back to you if I have questions and would you be willing to review my solution?

**Comment by rdmueller** [comment]
@p-goetz sure, I can review your solution. No problem.

**Comment by programming-wolf** [comment]
That’s basically what I had planned and in mind. Just not the time (and Gradle knowledge) to do it, yet.

**Comment by rdmueller** [comment]
@programming-wolf - that's the nice thing about those gradle tasks written in Groovy - you just write a Groovy Script and don't need too much Gradle know how :-)

**Comment by p-goetz** [comment]
@rdmueller I have taken a first shot at this and was able to create a list of learning objectives. I don't know how to make this a real listing with references to the pages in the PDF, though. Could you please have a look at the commit above and point me to some information on how to do this? 
I am also interested in your feedback on what to improve, as I am not very fluent in Groovy and Gradle. 
Thank you very much!

**Comment by gernotstarke** [comment]
first proposal: ignore page numbers, the "list" of learning goals is ok for a first step.

second idea: 
Asciidoc has a feature that provides automatic anchors to headings - so we don't need to write these anchors manually... we could "hijack" this feature to hyperlink. Then we would have "clickable" learning-goals in the Table-of-LGs.

third idea: have a look how asciidoctor creates the ToC... and copy this behavior for the ToLGs.

fourth version (gold plated): somehow (no idea how) we create the pdf, extract the page numbers from the pdf and "patch" these in the Table-of-LGs. Seems overly complicated.

**Comment by aheusingfeld** [comment]
I might be wrong, but isn’t this „add the links and page numbers to the ToLG“ exactly what asciidoctor already does for the headings and ToC? If I remember correctly there is a similar functionality build in for glossaries/indexes. You might want to send a mail to the mailinglist as to how the existing functionality can be used for our ToLG - in the end it’s only specifically „tagged“ (or unfortunately only specifically _formatted_ - headings, right?

**Comment by p-goetz** [comment]
Thanks for your feeedback. I have added the standard Asciidoc references pointing to the ids of the learning goals. This works inside the PDF and HTML output. 
I have also tried - unsuccessfully - to figure out how asciidoctor adds the page references in the PDF output. I asked for help around this on the discussion forum. Let's see what answer we get.

**Comment by gernotstarke** [comment]
The current (in RC4) list of learning goals seems sufficient for my taste - although it's lacking page numbers... at least we have hyperlinks. I close this issue.

**Comment by rdmueller** [comment]
@p-goetz sorry, I am a bit late to the party. It seems that you code works fine, so that's great.
When I take a look at your code, it seems that your code is more verbose than it has to be in Groovy.

So, here is what I would change:

Constructor (https://github.com/isaqb-org/curriculum-foundation/blob/V5-RC5/scripts/includeLearningObjectives.gradle#L11):
Groovy has default contructors with names parameters for all classes. So, you don't need this contructor and can do a

    def lo =   new LearningObjective(id: "id", title: "title", chapter: "5", chapterIndex: "6")

instead. 

Data-Class: why do you even use a class? You can use a Map:

    def lo =  [id: "id", title: "title", chapter: 5, chapterIndex: 6]

collectLearningObjectives: I like the way you handle the regular expressions! That's Groovy!

I think I would write the while loop this way:

                    learningObjectives.add(
                        new LearningObjective(id: matcher[1], 
                                              title: matcher[2], 
                                              chapter: matcher[3], 
                                              chapterIndex: matcher[4])
                    )

Sorting: can't we write the sort simpler?

        learningObjectives.sort { a, b ->
            if(a.chapter == b.chapter) {
                a.chapterIndex <=> b.chapterIndex
            } else {
                a.chapter <=> b.chapter
            }
        }

isn't that the same?

        learningObjectives.sort { a, b ->
                (a.chapter + a.chapterIndex) <=> (b.chapter + b.chapterIndex)
        }

If it is the same, I think it is short enough inline it :-)

compileLearningObjectives: I am a bit surprised by the line

        def content = ''<<''

which concatenates (`<<`) two empty Strings (`''`). I guess

        def content = ''

yields the same result. 
Update: got it: it creates a StringBuilder! cool trick!!

And I have never seen the `<<=` operater. I think `<<` does the same.

btw: instead of 

    "== " + headline + "\n\n"

you can also write

    "== ${headline}\n\n"

it is interesting to see how you code with closures and the `ex.`-namespace. I guess thismakes the code more readable. I am used to a script style whyre I just write the code down in a linear way. 
When I notice that I can re-use something, I create a closure just as a `def`-statement.

I hope this feedback is of some help :-)
