### ISSUE TITLE
LG 02-04: "Qualitätsanforderungen formulieren": können oder wissen?

### ISSUE THREAD

**Issue by kraemerdr** [isaqb-org/curriculum-foundation#597]
In Anlehnung an #539 sollte auch die Zielsetzung von Kapitel 2 leicht angepasst werden:

Alt: "Sie können solche Anforderungen mit Hilfe von Szenarien formulieren."
Neu: "Sie wissen, wie solche Anforderungen durch Szenarien beschrieben werden können."

Ersteres suggeriert, dass der Architekt für diese Aufgabe zuständig ist, was ich ähnlich wie @rhoadesre für falsch halte. Letzteres lässt hingegen bewusst offen, wer am Ende tatsächlich die Szenarien formuliert. Optimalerweise handelt es sich um einen Requirements Engineer, notfalls übernimmt es - nach Absprache - der Architekt.

**Comment by dkraemer-anderScore** [comment]
Gleiches gilt auch für LG 02-04:

Alt: "können Szenarien für gegebene Qualitäten mit Kontext, Stimulus und Reaktion oder Messmethode
formulieren (R1)"

Neu: "wissen, wie Szenarien für gegebene Qualitäten mit Kontext, Stimulus und Reaktion oder Messmethode
formuliert werden können (R1)"

**Comment by rhoadesre** [comment]
> In Anlehnung an #539 sollte auch die Zielsetzung von Kapitel 2 leicht angepasst werden:
> 
> Alt: "Sie können solche Anforderungen mit Hilfe von Szenarien formulieren." Neu: "Sie wissen, wie solche Anforderungen durch Szenarien beschrieben werden können."
> 
Ich fände es in Ordnung, wenn die Architekten Szenarien schreiben, um die Qualtätsanforderungen zu klären, die danach ggf. selbst als Anforderungen aufgenommen werden.

**Comment by dkraemer-anderScore** [comment]
Fände ich auch vertretbar. Es sollte nur deutlich werden, dass der Architekt bei der Spezifikation von Qualitätsanforderungen (mittels Szenarien) maximal in unterstützender Funktion agiert.

**Comment by programming-wolf** [comment]
Das sehe ich anders. Ganz oft müssen die Architekt:innen diese Szenarien schreiben oder gar Qualitätsanforderungen erarbeiten, da es sonst niemanden gibt, die das tun (können).

**Comment by dkraemer-anderScore** [comment]
In der Praxis ist das vermutlich sogar eher die Regel als die Ausnahme. Das heißt allerdings nicht, dass ein solches Vorgehen richtig ist. Die Erhebung von funktionalen **und** Qualitätsanforderungen (sowie Rahmenbedingungen) sehe ich originär als Aufgabe der Requirements Engineers - deshalb heißen sie schließlich so. ;-)

**Comment by ulibecker** [comment]
Ich bin dafür, das Lernziel so zu belassen. Ich sehe das als grundlegendes Handwerkszeug, daher passt "können".

**Comment by gernotstarke** [comment]
Ich bin ebenfalls für belassen. Wir haben das auch FLWG-intern schon oft diskutiert - und imho suggeriert die aktuelle Formulierung NICHT, welche Rolle / Person das konkret übernehmen soll.

Ich finde es wichtig zu betonen, dass Architekt:innen das KÖNNEN sollen... ob sie's dann tun, steht ja auf einem anderen Blatt.

**Comment by rhoadesre** [comment]
Ich bin nach wie vor für die Formulierungen von Daniel: 

> Sie wissen, wie solche Anforderungen durch Szenarien beschrieben werden können.
> wissen, wie Szenarien für gegebene Qualitäten mit Kontext, Stimulus und Reaktion oder Messmethode formuliert werden können (R1)

Dadurch bleibt die Fähigkeit, Szenarien formulieren zu können, ohne, dass es die Frage bzgl. Verantwortlichkeit angeht.

**Comment by gernotstarke** [comment]
I have a VERY STRONG objection against Daniels proposal, as the ability to formulate quality requirements in precise, decidable and measurable way is an ESSENTIAL capability for architects.

Beeing able to formulate _good_ Q-scenarios is part of many CPSA-Advanced examinations, and MUST BE TAUGHT and practiced in foundation trainings.

It is DEFINITELY not sufficient to _know about_, people need to be able to DO that practically.

Therefore I stick with my "wontfix".

**Comment by gernotstarke** [comment]
ok - I close this issue again, and will create an ADR adressing this topic.

**Comment by rhoadesre** [comment]
Anstatt einfach selbst zu entscheiden, den Issue zu schließen und eine ADR dafür zu erstellen, wünsche ich mir, dass wir eine Lösung finden, dass für uns alle Akzeptabel ist. 
Offensichtlich gibt es unterschiedliche Meinung hierzu. Ich habe auch eine sehr starke Meinung und möchte eine gemeinsame Lösung finden.

**Comment by rhoadesre** [comment]
I've voiced my opinion on several other occasions, including in the following issues:
#15, #299 , #396 , #539 , and is this issues #597.

I'm fine with the statement that architects shall be able to formulate quality scenarios. 

It seems to me that we differ mostly on why the architect should formulate the scenarios. One party believes that they should be able to formulate scenarios as requirements, the other believes they should formulate scenarios to clarify requirements. A subtle, but for me, very important difference. 

I disagree as stongly with Genots position regarding the capability of architects to formulate requirements as he strongly fights for it. As Daniel said, that's why there's a role of Requirements Engineer, Product Owner, etc. If they are not available, somebody needs to take over this role. It is, of course, possilbe that the same person assumes the role of Software Architect and Requirements Engineer. But the activities for the roles (not the person) should be differentiated. 

An architect that defines requirements opens themselves up for legal issues, political issues, etc.

**Comment by rhoadesre** [comment]
Concretely, I propose the following: 

In LG 01-03 (already implemented): 
Clarify and scrutinize the requirements and constraints. Coordinate and agree on any necessary refinements with the corresponding stakeholders.

In LG 02-04: 
Can formulate scenarios for given qualities with context, stimulus, response, and measurement for a variety of purposes, e.g., to clarify requirements, provide input for architecture assessments, etc. (R1)

Would this be acceptable for everyone?

**Comment by dkraemer-anderScore** [comment]
> I have a VERY STRONG objection against Daniels proposal, as the ability to formulate quality requirements in precise, decidable and measurable way is an ESSENTIAL capability for architects.

From my point of view it should primarily be an essential capability of **requirements engineers** which a lot of them seem to lack unfortunately. In practice this is where an architect comes into play, but still defining and documenting requirements is other people's responsibility by their job title.

> Beeing able to formulate good Q-scenarios is part of many CPSA-Advanced examinations, and MUST BE TAUGHT and practiced in foundation trainings.

It is not our objective to abandon them, but to explicitely limit their usage by architects to supporting purposes. That does **not** make them less important for foundation trainings.

> Szenarien zu formulieren ist ein absolutes Muss und keine optionale Leistung des Softwarearchitekten.

Could you be a bit more specific about this? Why is formulating scenarios (i.e. quality **requirements**) something an architect **should do** instead of a **requirements** engineer?

> Rather than simply deciding to close the issue and create an ADR for it, I would like us to find a solution that is acceptable to all of us.

Almost sounds like a community-based approach targeted towards consentual (not necessarily consensual) decisions for a course supposed to be held by a lot of different trainers. I like.

> Would this be acceptable for everyone?

Thumbs up from my side.

**Comment by alxlo** [comment]
My 0,02€ on this, because it's such a highly debated topic. Let me start with, what I've been told by Stefan Tilkov "Architects go where they are needed." As this is no real argument but simple appeal to authority, my argument on this is, that it is definitely a required skill for architects to differentiate between scenarios that are not **useful** to make architectural decisions and those that help you. To master this skill it's IMHO essential to be able to formulate "good" scenarios or provide proposals for their improvement.
Furthermore one has to cope with, that sometimes it not possible or (economically) viable to have good, measurable scenarios with a clear definition of done. My stance on this is: Work with what you have, paint it as a possible risk but definitely make sure it is documented. "The app should have a good usability." is not a super useful scenario but for me it is important to have this stakeholder concern stated somewhere so that one can come up with a plan to work turn this into something more tangible.

**Comment by Hruschka** [comment]
It is not only about quality scenarios: Architects have to be able to add enough precision to every kind of requirement that is vague. Of course in cooperation with stakeholders that came up with vague requirements in the first place. Therefore, I suggest that architects have to master this skill of questioning imprecise requirements and suggest (measurable) improvements for them.

**Comment by alxlo** [comment]
I agree with @gernotstarke and @Hruschka 's position on this. Even if there are analysts who's job it is to do this, just **knowing how to** doesn't get you far enough. As an architect you have to provide options to your stakeholders and therefore **must be able to** formulate precise requirements.
You don't have to master all the techniques for eliciting requirements from stakeholders to the extent a requirement engineer does,  but it helps a lot to not only know the ropes, but also to come up with good proposals.

**Comment by ulibecker** [comment]
As written above, I am also I favor of "can formulate such requirements". Of course architects can't just make up requirements without involving relevant stakeholders, but the same is also true for requirements engineers.

**Comment by rhoadesre** [comment]
@Axlo, @Hruschka: 

As stated in my last post and here (see below), the proposal is not to just "know", but to "can formulate". 

>Can formulate scenarios for given qualities with context, stimulus, response, and measurement for a variety of purposes, e.g., to clarify requirements, provide input for architecture assessments, etc. (R1)

@Hruschka:
>question imprecise requirements and suggest (measurable) improvements for them
I 100% agree with you that we should have the skills to "question imprecise requirements and suggest (measurable) improvements for them". If the statement is written this way, it would be 100% acceptable for me. I'm simply against "defining" requirements (incl. quality scenarios, which can be used as a form of requirement). For me when you "formulate" something you also "define" it.

@Hruschka: 
> Architects have to be able to add enough precision to every kind of requirement that is vague
Careful. By "adding precision", there is a good chance that you change the original intention of the requirement. It's better to make a proposal and coordinate the change to the requirement with the corresponding stakeholder 

@Axlo: 
>As an architect you have to provide options to your stakeholders and therefore must be able to formulate precise requirements.
You should clarify requirements and provide implementation options for the specified requirements. If it helps to formulate a scenario in order to clarify a requirement, I don't have a problem with this.

**Comment by mikesperber** [comment]
tl;dr I agree with @gernotstarke , @Hruschka , @alxlo.

I understand the desire to let the requirements engineers do their job: However, the allocation of particular responsibilities and tasks to specific roles and people is not really our job, IMHO: The project/employer/customer will do this. In particular, codifying this desire effectively means telling the REs what job they should do, when our target audience is the architects.

Should we think otherwise, this is not the LG for it - there should be another one saying "Architects understand that they should defer to requirements specialists when it comes to the formulation of requirements, if available." (I'm not proposing adding such an LG.)

**Comment by rhoadesre** [comment]
> However, the allocation of particular responsibilities and tasks to specific roles and people is not really our job, 

We're not trying to define the job of the requirements engineer. We're trying to define what an architect does, within the context that other roles also exist (e.g., PM, PO, RE, etc.)

**Comment by rhoadesre** [comment]
There's a lot of discussion on this issue. And it's obvious that there are differing opinions. 
I would like to discuss a specific formulation that everyone is happy with. 
Is the following specific formulation acceptable? Or are there other specific proposals?

>Can formulate scenarios for given qualities with context, stimulus, response, and measurement for a variety of purposes, e.g., to clarify requirements, provide input for architecture assessments, etc. (R1)

**Comment by bertjan** [comment]
I'm with @gernotstarke here. Regardless of whose work it is, architects play an essential role in getting quality requirements clearly defined. In my experience, architects are often the *only* type of people who are capable of precisely defining quality requirements, simply because others in the project do not know how (they won't get much further than "secure", "scalable", "available" which says close to nothing...)
So I do agree that being able to formulate /  clarify requirements for quality attributes is an essential skill for software architects. If the requirements engineer is able to do this, that's fine. But if the requirements engineer is not, the architect must be capable in this.

Looking forward:
For my understanding and overview: current wording in https://github.com/isaqb-org/curriculum-foundation/blob/main/docs/02-requirements/LG-02-04.adoc is:
> can formulate scenarios for given qualities containing context, stimulus, and reaction or method of measurement (R1)

@rhoadesre your proposal is to change this to the following, right?
> Can formulate scenarios for given qualities with context, stimulus, response, and measurement for a variety of purposes, e.g., to clarify requirements, provide input for architecture assessments, etc. (R1)

**Comment by rhoadesre** [comment]
> @rhoadesre your proposal is to change this to the following, right?
> 
> > Can formulate scenarios for given qualities with context, stimulus, response, and measurement for a variety of purposes, e.g., to clarify requirements, provide input for architecture assessments, etc. (R1)

Correct.

**Comment by ulibecker** [comment]
@rhoadesre‘s propososal is fine for me

**Comment by mahboubagharbi** [comment]
I agree with "can (or be able to) formulate such requirements"

**Comment by mikesperber** [comment]
@rhoadesre‘s propososal is fine for me

**Comment by bertjan** [comment]
I'm OK with @rhoadesre‘s proposal as well.

**Comment by gernotstarke** [comment]
then I open PR #654 for this - adjusting LG-02-04 according to the proposal above.

**Comment by rhoadesre** [comment]
So I definitely learned that I will represent both sides in my upcoming classes. I have a strong opinion on the topic, but it's just as important to represent the other opinions. 

Thanks for the lively discussions and opinions!
