### ISSUE TITLE
LG 02-01 DE: Business-Analyse or Business-Analyst:in?

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#632]
"Businss-Analyse" should be "Business-Analyst"

**Comment by gernotstarke** [comment]
then it need to be "Business-Analyst:in", as we use the gendered form in German.

I suggest to leave the role-name ("Business-Analyse") in German.

**Comment by rhoadesre** [comment]
Is "Business-Analyse" a role? I'm not German, so I'm open.

**Comment by gernotstarke** [comment]
Yes, imho it is a role name, like "Requirements Engineering". 

If it's ok for you, can we close your PR #633 without merging!

**Comment by rhoadesre** [comment]
I would say, "Requirements Engineering" is also not a role, but I don't have a strong opinion. 
Go ahead and close this without merging. That's fine with me.

**Comment by alxlo** [comment]
Requirements Engineering' and 'Business-Analyse' sound to me more like business areas or (scientific) disciplines rather than roles. This will certainly lead to questions from some people and increases the potential for misunderstandings, but I don't have any particular preferences here, and since I don't have a better idea, I'm in favor of closing without merging.
