### ISSUE TITLE
New LG: Socio-technical systems

### ISSUE THREAD

**Issue by mistertakai** [isaqb-org/curriculum-foundation#657]
I'd like to add a new LG to the curriculum:

**Understand and explain the feedback loop of a socio-technical system.**

- Socio-technical systems form a feedback loop between users and system genesis [LL23]
- Tendencies of the social field of a software system should be recognised and reflected in the architectural design [OS18]
- Architects can classify the relationship of organisations within a system according to Evans [EE03]
- The nature of organisational relationships influences system design [EE03]

Literature:

- [EE03] Eric Evans, Domain-Driven Design: Tackling Complexity in the Heart of Software, AddisonWesley, 2003
- [LL23] Lehman's Laws of Software Evolution, online available here: - https://en.wikipedia.org/wiki/Lehman%27s_laws_of_software_evolution - Continuing growth
- [OS18] Otto Scharmer, The Essentials of Theory U: Core Principles and Applications, San Francisco, Berrett-Koehler Publishers, 2018

**Comment by sippsack** [comment]
I'm a bit sceptical. Why should we speak about this in Foundation which is already fully packed. I suppose you want to raise awareness. But in my opinion it would be only R3 and there for optional

**Comment by alxlo** [comment]
We've removed the old **LG 1-3: Understand Software Architecture as Part of the Software Lifecycle (R2)** from the curriculum 

> Software architects understand their tasks and can integrate their results into the overall lifecycle of IT
> systems. They can:
> • identify the consequences of changes in requirements, technologies, or the system environment in
> relation to software architecture
> • elaborate on relationships between IT-systems and the supported business and operational
> processes

This is where this could have fitted in and I honestly do not remember why we eliminated that LG because "coping with change" is a very central thing and I can't find anything in the curriculum related to that topic anymore.

Very(!) reluctantly (@sippsack 's observation about the overwhelming size of the curriculum is well noted and something I very much relate to) I would like to ask if we should reconsider this point. Understanding the ongoing evolution of an IT system over time is IMHO quite important for architects. 

@gernotstarke What do you think?

**Comment by alxlo** [comment]
On the content itself: That's 50y old research (which s neither a good or a bad sign) and I never ever in my career stumbled upon this, I'd rather talk about Rajlich and Bennet's Staged Model for the Software Life Cycle (http://www.dsc.ufcg.edu.br/~garcia/cursos/dglobal_software/artigos/staged_modelsw.pdf) but Lehmanns' Law might provide some background on the principles. 

If (and that's a very big IF) we reintroduce this learning goal the general understanding of this should be R2 with all the additional details being R3.

**Comment by gernotstarke** [comment]
added a few more people to the assignee-list to get more feedback.

**Comment by mahboubagharbi** [comment]
It would make sense to specifically integrate the topic of socio-technical systems into the soft skills curriculum for software architects, rather than placing it in the foundation curriculum. Here are some aspects that could be considered:
1. Interdisciplinary Communication: Software architects should be able to communicate effectively with various stakeholders, including developers, product managers, and end users. 
2. Understanding Team Dynamics: Understanding group behavior and team dynamics can help architects work better in agile environments. 
3. Stakeholder Management: Addressing the identification and management of stakeholder interests and influences could be valuable. This includes techniques for stakeholder analysis and strategic decision-making.
4. Influence of Social Aspects on Design Decisions: Raising awareness of how social factors impact technological decisions, such as how cultural differences can affect implementation.
5. Conflict Resolution and Negotiation: Skills for resolving conflicts that may arise within teams or with stakeholders are crucial. Role-plays or simulations could help develop these skills.

**Comment by rhoadesre** [comment]
> It would make sense to specifically integrate the topic of socio-technical systems into the soft skills curriculum for software architects, rather than placing it in the foundation curriculum. Here are some aspects that could be considered:

I second this suggestion - even though it means that I have work to do to update the Soft-Skills curriculum and my corresponding handouts.  :-) The Soft-Skills curriculum is already really (!) full, but the topics belong more in this area.

**Comment by programming-wolf** [comment]
SOFT is also still an RC, so we could add it for the new release.

**Comment by ulibecker** [comment]
It sure is a relevant topic. However, as @sippsack wrote, the foundation curriculum is already pretty packed, so one could only handle the topic very superficially, and I see no value in that. Adding it to SOFT sounds good to me.

**Comment by michaelpog** [comment]
I think this is important. But the foundation level curriculum is not an exhaustive list of topics software architects need to know and be aware of.
So I think it should be as part of a CPSA-A modules instead of being part of the foundation level curriculum.

**Comment by alxlo** [comment]
There are several advanced modules where the details of this topic might fit in. There is some overlap with SOFT, but there might be other advanced curricula as well - but that's no the point I wanted to make here.

My point is: currently we no longer talk **at all** about the long term impact of software architecture on the evolution of a system. And that's something I'm **seriously** worried about for quite a number of reasons.

Sorry for sounding a bit dramatic here, but making FL students think about what consequences their architectural decision have in the long run is one of the things that I deem to be fundamental. It's one of the big WHY's of why we should spend effort on any kind of systems architecture in the first place.

**Comment by gbeine** [comment]
Please be aware that socio-technical systems is a well defined term in social sciences and none of the mentioned sources uses it correctly ;-)

**Comment by gernotstarke** [comment]
@alxlo and myself summarized this discussion with the following decisions:

[ ] The topic of "socio-technical" shall be handled in another (CPSA-A) curriculum. Documented as ADR-011
[ ] The topic of "long-term impact of software architecture" will be added as LG 01-03 (similar to "lifecycle" LG-01-03 from V-2023) 
This leads to modified numbering of LG's within section 01.
[ ] We introduce a few references to socio-technical systems in LG-01-03.

Put all related changes into branch `Issue-#657-socio-technical-systems-etc`
